var hierarchy =
[
    [ "Application", null, [
      [ "EasyVideoEdition.App", "class_easy_video_edition_1_1_app.html", null ],
      [ "EasyVideoEdition.App", "class_easy_video_edition_1_1_app.html", null ],
      [ "EasyVideoEdition.App", "class_easy_video_edition_1_1_app.html", null ]
    ] ],
    [ "EasyVideoEdition.ViewModel.AudioAddingViewModel", "class_easy_video_edition_1_1_view_model_1_1_audio_adding_view_model.html", null ],
    [ "EasyVideoEdition.ViewModel.AudioEditionViewModel", "class_easy_video_edition_1_1_view_model_1_1_audio_edition_view_model.html", null ],
    [ "EasyVideoEdition.ViewModel.ChapterViewModel", "class_easy_video_edition_1_1_view_model_1_1_chapter_view_model.html", null ],
    [ "EasyVideoEdition.ViewModel.IBaseViewModel", "interface_easy_video_edition_1_1_view_model_1_1_i_base_view_model.html", [
      [ "EasyVideoEdition.ViewModel.NullViewModel", "class_easy_video_edition_1_1_view_model_1_1_null_view_model.html", null ],
      [ "EasyVideoEdition.ViewModel.OpeningViewModel", "class_easy_video_edition_1_1_view_model_1_1_opening_view_model.html", null ],
      [ "EasyVideoEdition.ViewModel.SaveFileViewModel", "class_easy_video_edition_1_1_view_model_1_1_save_file_view_model.html", null ],
      [ "EasyVideoEdition.ViewModel.SubtitlesViewModel", "class_easy_video_edition_1_1_view_model_1_1_subtitles_view_model.html", null ]
    ] ],
    [ "ICommand", null, [
      [ "RelayCommand", "class_relay_command.html", null ]
    ] ],
    [ "IComponentConnector", null, [
      [ "EasyVideoEdition.MainWindow", "class_easy_video_edition_1_1_main_window.html", null ],
      [ "EasyVideoEdition.MainWindow", "class_easy_video_edition_1_1_main_window.html", null ],
      [ "EasyVideoEdition.View.Audio_adding", "class_easy_video_edition_1_1_view_1_1_audio__adding.html", null ],
      [ "EasyVideoEdition.View.Audio_adding", "class_easy_video_edition_1_1_view_1_1_audio__adding.html", null ],
      [ "EasyVideoEdition.View.Audio_edition", "class_easy_video_edition_1_1_view_1_1_audio__edition.html", null ],
      [ "EasyVideoEdition.View.Audio_edition", "class_easy_video_edition_1_1_view_1_1_audio__edition.html", null ],
      [ "EasyVideoEdition.View.BasicUserControl", "class_easy_video_edition_1_1_view_1_1_basic_user_control.html", null ],
      [ "EasyVideoEdition.View.BasicUserControl", "class_easy_video_edition_1_1_view_1_1_basic_user_control.html", null ],
      [ "EasyVideoEdition.View.BasicUserControlAudioAdding", "class_easy_video_edition_1_1_view_1_1_basic_user_control_audio_adding.html", null ],
      [ "EasyVideoEdition.View.BasicUserControlAudioAdding", "class_easy_video_edition_1_1_view_1_1_basic_user_control_audio_adding.html", null ],
      [ "EasyVideoEdition.View.BasicUserControlAudioEdition", "class_easy_video_edition_1_1_view_1_1_basic_user_control_audio_edition.html", null ],
      [ "EasyVideoEdition.View.BasicUserControlAudioEdition", "class_easy_video_edition_1_1_view_1_1_basic_user_control_audio_edition.html", null ],
      [ "EasyVideoEdition.View.BasicUserControlChapters", "class_easy_video_edition_1_1_view_1_1_basic_user_control_chapters.html", null ],
      [ "EasyVideoEdition.View.BasicUserControlChapters", "class_easy_video_edition_1_1_view_1_1_basic_user_control_chapters.html", null ],
      [ "EasyVideoEdition.View.BasicUserControlSubtitles", "class_easy_video_edition_1_1_view_1_1_basic_user_control_subtitles.html", null ],
      [ "EasyVideoEdition.View.BasicUserControlSubtitles", "class_easy_video_edition_1_1_view_1_1_basic_user_control_subtitles.html", null ],
      [ "EasyVideoEdition.View.BasicUserControlVisualEdition", "class_easy_video_edition_1_1_view_1_1_basic_user_control_visual_edition.html", null ],
      [ "EasyVideoEdition.View.BasicUserControlVisualEdition", "class_easy_video_edition_1_1_view_1_1_basic_user_control_visual_edition.html", null ],
      [ "EasyVideoEdition.View.Chapters_adding", "class_easy_video_edition_1_1_view_1_1_chapters__adding.html", null ],
      [ "EasyVideoEdition.View.Chapters_adding", "class_easy_video_edition_1_1_view_1_1_chapters__adding.html", null ],
      [ "EasyVideoEdition.View.DoubleSlider", "class_easy_video_edition_1_1_view_1_1_double_slider.html", null ],
      [ "EasyVideoEdition.View.DoubleSlider", "class_easy_video_edition_1_1_view_1_1_double_slider.html", null ],
      [ "EasyVideoEdition.View.Open", "class_easy_video_edition_1_1_view_1_1_open.html", null ],
      [ "EasyVideoEdition.View.Open", "class_easy_video_edition_1_1_view_1_1_open.html", null ],
      [ "EasyVideoEdition.View.Save", "class_easy_video_edition_1_1_view_1_1_save.html", null ],
      [ "EasyVideoEdition.View.Save", "class_easy_video_edition_1_1_view_1_1_save.html", null ],
      [ "EasyVideoEdition.View.Subtitles_adding", "class_easy_video_edition_1_1_view_1_1_subtitles__adding.html", null ],
      [ "EasyVideoEdition.View.Subtitles_adding", "class_easy_video_edition_1_1_view_1_1_subtitles__adding.html", null ],
      [ "EasyVideoEdition.View.Visual_adding", "class_easy_video_edition_1_1_view_1_1_visual__adding.html", null ],
      [ "EasyVideoEdition.View.Visual_adding", "class_easy_video_edition_1_1_view_1_1_visual__adding.html", null ],
      [ "EasyVideoEdition.View.Visual_edition", "class_easy_video_edition_1_1_view_1_1_visual__edition.html", null ],
      [ "EasyVideoEdition.View.Visual_edition", "class_easy_video_edition_1_1_view_1_1_visual__edition.html", null ],
      [ "Interface_v1.View.Ajout_audio", "class_interface__v1_1_1_view_1_1_ajout__audio.html", null ],
      [ "Interface_v1.View.Ajout_sous_titres", "class_interface__v1_1_1_view_1_1_ajout__sous__titres.html", null ],
      [ "Interface_v1.View.Ajout_visuel", "class_interface__v1_1_1_view_1_1_ajout__visuel.html", null ],
      [ "Interface_v1.View.Edition_audio", "class_interface__v1_1_1_view_1_1_edition__audio.html", null ],
      [ "Interface_v1.View.Edition_visuel", "class_interface__v1_1_1_view_1_1_edition__visuel.html", null ],
      [ "Interface_v1.View.Page1", "class_interface__v1_1_1_view_1_1_page1.html", null ]
    ] ],
    [ "EasyVideoEdition.Model.IFile", "interface_easy_video_edition_1_1_model_1_1_i_file.html", [
      [ "EasyVideoEdition.Model.Picture", "class_easy_video_edition_1_1_model_1_1_picture.html", null ],
      [ "EasyVideoEdition.Model.Video", "class_easy_video_edition_1_1_model_1_1_video.html", null ]
    ] ],
    [ "IMultiValueConverter", null, [
      [ "EasyVideoEdition.Utils.InstructionsTabsConverter", "class_easy_video_edition_1_1_utils_1_1_instructions_tabs_converter.html", null ],
      [ "EasyVideoEdition.Utils.TabSizeConverter", "class_easy_video_edition_1_1_utils_1_1_tab_size_converter.html", null ]
    ] ],
    [ "INotifyPropertyChanged", null, [
      [ "EasyVideoEdition.ObjectBase", "class_easy_video_edition_1_1_object_base.html", [
        [ "EasyVideoEdition.MainViewModel", "class_easy_video_edition_1_1_main_view_model.html", null ],
        [ "EasyVideoEdition.Model.FileBrowser", "class_easy_video_edition_1_1_model_1_1_file_browser.html", null ],
        [ "EasyVideoEdition.Model.MainVideo", "class_easy_video_edition_1_1_model_1_1_main_video.html", null ],
        [ "EasyVideoEdition.Model.StoryBoard", "class_easy_video_edition_1_1_model_1_1_story_board.html", null ],
        [ "EasyVideoEdition.Model.StoryBoardElement", "class_easy_video_edition_1_1_model_1_1_story_board_element.html", null ],
        [ "EasyVideoEdition.Model.Subtitle", "class_easy_video_edition_1_1_model_1_1_subtitle.html", null ],
        [ "EasyVideoEdition.Model.Subtitles", "class_easy_video_edition_1_1_model_1_1_subtitles.html", null ],
        [ "EasyVideoEdition.Model.Video", "class_easy_video_edition_1_1_model_1_1_video.html", null ],
        [ "EasyVideoEdition.Model.VideoConverter", "class_easy_video_edition_1_1_model_1_1_video_converter.html", null ],
        [ "EasyVideoEdition.Model.VideoPlayer", "class_easy_video_edition_1_1_model_1_1_video_player.html", null ],
        [ "EasyVideoEdition.ViewModel.NullViewModel", "class_easy_video_edition_1_1_view_model_1_1_null_view_model.html", null ],
        [ "EasyVideoEdition.ViewModel.OpeningViewModel", "class_easy_video_edition_1_1_view_model_1_1_opening_view_model.html", null ],
        [ "EasyVideoEdition.ViewModel.SaveFileViewModel", "class_easy_video_edition_1_1_view_model_1_1_save_file_view_model.html", null ],
        [ "EasyVideoEdition.ViewModel.SubtitlesViewModel", "class_easy_video_edition_1_1_view_model_1_1_subtitles_view_model.html", null ],
        [ "EasyVideoEdition.ViewModel.VisualAddingViewModel", "class_easy_video_edition_1_1_view_model_1_1_visual_adding_view_model.html", null ]
      ] ]
    ] ],
    [ "InternalTypeHelper", null, [
      [ "XamlGeneratedNamespace.GeneratedInternalTypeHelper", "class_xaml_generated_namespace_1_1_generated_internal_type_helper.html", null ],
      [ "XamlGeneratedNamespace.GeneratedInternalTypeHelper", "class_xaml_generated_namespace_1_1_generated_internal_type_helper.html", null ]
    ] ],
    [ "Page", null, [
      [ "Interface_v1.View.Page1", "class_interface__v1_1_1_view_1_1_page1.html", null ]
    ] ],
    [ "UserControl", null, [
      [ "EasyVideoEdition.View.Audio_adding", "class_easy_video_edition_1_1_view_1_1_audio__adding.html", null ],
      [ "EasyVideoEdition.View.Audio_adding", "class_easy_video_edition_1_1_view_1_1_audio__adding.html", null ],
      [ "EasyVideoEdition.View.Audio_adding", "class_easy_video_edition_1_1_view_1_1_audio__adding.html", null ],
      [ "EasyVideoEdition.View.Audio_edition", "class_easy_video_edition_1_1_view_1_1_audio__edition.html", null ],
      [ "EasyVideoEdition.View.Audio_edition", "class_easy_video_edition_1_1_view_1_1_audio__edition.html", null ],
      [ "EasyVideoEdition.View.Audio_edition", "class_easy_video_edition_1_1_view_1_1_audio__edition.html", null ],
      [ "EasyVideoEdition.View.BasicUserControl", "class_easy_video_edition_1_1_view_1_1_basic_user_control.html", null ],
      [ "EasyVideoEdition.View.BasicUserControl", "class_easy_video_edition_1_1_view_1_1_basic_user_control.html", null ],
      [ "EasyVideoEdition.View.BasicUserControl", "class_easy_video_edition_1_1_view_1_1_basic_user_control.html", null ],
      [ "EasyVideoEdition.View.BasicUserControlAudioAdding", "class_easy_video_edition_1_1_view_1_1_basic_user_control_audio_adding.html", null ],
      [ "EasyVideoEdition.View.BasicUserControlAudioAdding", "class_easy_video_edition_1_1_view_1_1_basic_user_control_audio_adding.html", null ],
      [ "EasyVideoEdition.View.BasicUserControlAudioAdding", "class_easy_video_edition_1_1_view_1_1_basic_user_control_audio_adding.html", null ],
      [ "EasyVideoEdition.View.BasicUserControlAudioEdition", "class_easy_video_edition_1_1_view_1_1_basic_user_control_audio_edition.html", null ],
      [ "EasyVideoEdition.View.BasicUserControlAudioEdition", "class_easy_video_edition_1_1_view_1_1_basic_user_control_audio_edition.html", null ],
      [ "EasyVideoEdition.View.BasicUserControlAudioEdition", "class_easy_video_edition_1_1_view_1_1_basic_user_control_audio_edition.html", null ],
      [ "EasyVideoEdition.View.BasicUserControlChapters", "class_easy_video_edition_1_1_view_1_1_basic_user_control_chapters.html", null ],
      [ "EasyVideoEdition.View.BasicUserControlChapters", "class_easy_video_edition_1_1_view_1_1_basic_user_control_chapters.html", null ],
      [ "EasyVideoEdition.View.BasicUserControlChapters", "class_easy_video_edition_1_1_view_1_1_basic_user_control_chapters.html", null ],
      [ "EasyVideoEdition.View.BasicUserControlSubtitles", "class_easy_video_edition_1_1_view_1_1_basic_user_control_subtitles.html", null ],
      [ "EasyVideoEdition.View.BasicUserControlSubtitles", "class_easy_video_edition_1_1_view_1_1_basic_user_control_subtitles.html", null ],
      [ "EasyVideoEdition.View.BasicUserControlSubtitles", "class_easy_video_edition_1_1_view_1_1_basic_user_control_subtitles.html", null ],
      [ "EasyVideoEdition.View.BasicUserControlVisualEdition", "class_easy_video_edition_1_1_view_1_1_basic_user_control_visual_edition.html", null ],
      [ "EasyVideoEdition.View.BasicUserControlVisualEdition", "class_easy_video_edition_1_1_view_1_1_basic_user_control_visual_edition.html", null ],
      [ "EasyVideoEdition.View.BasicUserControlVisualEdition", "class_easy_video_edition_1_1_view_1_1_basic_user_control_visual_edition.html", null ],
      [ "EasyVideoEdition.View.Chapters_adding", "class_easy_video_edition_1_1_view_1_1_chapters__adding.html", null ],
      [ "EasyVideoEdition.View.Chapters_adding", "class_easy_video_edition_1_1_view_1_1_chapters__adding.html", null ],
      [ "EasyVideoEdition.View.Chapters_adding", "class_easy_video_edition_1_1_view_1_1_chapters__adding.html", null ],
      [ "EasyVideoEdition.View.DoubleSlider", "class_easy_video_edition_1_1_view_1_1_double_slider.html", null ],
      [ "EasyVideoEdition.View.DoubleSlider", "class_easy_video_edition_1_1_view_1_1_double_slider.html", null ],
      [ "EasyVideoEdition.View.DoubleSlider", "class_easy_video_edition_1_1_view_1_1_double_slider.html", null ],
      [ "EasyVideoEdition.View.Open", "class_easy_video_edition_1_1_view_1_1_open.html", null ],
      [ "EasyVideoEdition.View.Open", "class_easy_video_edition_1_1_view_1_1_open.html", null ],
      [ "EasyVideoEdition.View.Open", "class_easy_video_edition_1_1_view_1_1_open.html", null ],
      [ "EasyVideoEdition.View.Save", "class_easy_video_edition_1_1_view_1_1_save.html", null ],
      [ "EasyVideoEdition.View.Save", "class_easy_video_edition_1_1_view_1_1_save.html", null ],
      [ "EasyVideoEdition.View.Save", "class_easy_video_edition_1_1_view_1_1_save.html", null ],
      [ "EasyVideoEdition.View.Subtitles_adding", "class_easy_video_edition_1_1_view_1_1_subtitles__adding.html", null ],
      [ "EasyVideoEdition.View.Subtitles_adding", "class_easy_video_edition_1_1_view_1_1_subtitles__adding.html", null ],
      [ "EasyVideoEdition.View.Subtitles_adding", "class_easy_video_edition_1_1_view_1_1_subtitles__adding.html", null ],
      [ "EasyVideoEdition.View.Visual_adding", "class_easy_video_edition_1_1_view_1_1_visual__adding.html", null ],
      [ "EasyVideoEdition.View.Visual_adding", "class_easy_video_edition_1_1_view_1_1_visual__adding.html", null ],
      [ "EasyVideoEdition.View.Visual_adding", "class_easy_video_edition_1_1_view_1_1_visual__adding.html", null ],
      [ "EasyVideoEdition.View.Visual_edition", "class_easy_video_edition_1_1_view_1_1_visual__edition.html", null ],
      [ "EasyVideoEdition.View.Visual_edition", "class_easy_video_edition_1_1_view_1_1_visual__edition.html", null ],
      [ "EasyVideoEdition.View.Visual_edition", "class_easy_video_edition_1_1_view_1_1_visual__edition.html", null ],
      [ "Interface_v1.View.Ajout_audio", "class_interface__v1_1_1_view_1_1_ajout__audio.html", null ],
      [ "Interface_v1.View.Ajout_sous_titres", "class_interface__v1_1_1_view_1_1_ajout__sous__titres.html", null ],
      [ "Interface_v1.View.Ajout_visuel", "class_interface__v1_1_1_view_1_1_ajout__visuel.html", null ],
      [ "Interface_v1.View.Edition_audio", "class_interface__v1_1_1_view_1_1_edition__audio.html", null ],
      [ "Interface_v1.View.Edition_visuel", "class_interface__v1_1_1_view_1_1_edition__visuel.html", null ]
    ] ],
    [ "EasyVideoEdition.Model.videoScreenshotCreator", "class_easy_video_edition_1_1_model_1_1video_screenshot_creator.html", null ],
    [ "EasyVideoEdition.Model.VideoTimer", "class_easy_video_edition_1_1_model_1_1_video_timer.html", null ],
    [ "EasyVideoEdition.ViewModel.VisualEditionViewModel", "class_easy_video_edition_1_1_view_model_1_1_visual_edition_view_model.html", null ],
    [ "Window", null, [
      [ "EasyVideoEdition.MainWindow", "class_easy_video_edition_1_1_main_window.html", null ],
      [ "EasyVideoEdition.MainWindow", "class_easy_video_edition_1_1_main_window.html", null ],
      [ "EasyVideoEdition.MainWindow", "class_easy_video_edition_1_1_main_window.html", null ]
    ] ]
];